name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: spitharepo/buildpack:1.19.4-centos7

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: make -C docker
