name: kafka-datagen

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    
    - name: Build And Push
      env:
        NAME: spitharepo
        REPO: kafka-datagen 
      run: |
        VERSION=`cat ./VERSION`
        SVERSION=`echo $VERSION | cut -d'.' -f1-2`
        MVERSION=`echo $VERSION | cut -d'.' -f1`
        
        make -C docker docker
        docker tag $REPO:latest $NAME/$REPO:latest
        docker tag $REPO:latest $NAME/$REPO:$VERSION
        docker tag $REPO:latest $NAME/$REPO:$SVERSION
        docker tag $REPO:latest $NAME/$REPO:$MVERSION
        docker push $NAME/$REPO:$VERSION
        docker push $NAME/$REPO:$SVERSION
        docker push $NAME/$REPO:$MVERSION
        docker push $NAME/$REPO:latest
